# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1M9-Z8XlZ-1Ln6ugr2DYrZD_U81AulZ97
"""

def read_file_last(filename, n):
    """Принимает на вход имя txt файла и целое положительное число n, возвращает список последних n строк этого файла."""
    with open(filename, 'r', encoding='utf-8') as file:
        lines = file.readlines()

    # Удаляем символы переноса строки и возвращаем последние n строк
    stripped_lines = [line.strip() for line in lines]
    return stripped_lines[-n:]